# Generated by Django 5.2 on 2025-04-11 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
